# Generated by Django 5.2.17 on 2026-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='Student', error_messages='Enter Your Name Again', max_length=255)),
                ('s_topics', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('s_mastery', models.FloatField(blank=True, null=True, verbose_name='Mastery')),
                ('s_av_time', models.IntegerField(error_messages='Enter Available Time to Study per day(hours)', help_text='Enter Available Time to Study per day(hours)')),
            ],
        ),
    ]
