# Generated by Django 5.2.17 on 2026-08-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentState',
            fields=[
                ('name', models.CharField(default='Student', max_length=255, primary_key=True, serialize=False)),
                ('topics', models.CharField(blank=True, default='none', max_length=255, null=True)),
                ('mastery', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('av_time', models.IntegerField(default=0)),
                ('join_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('hours_free', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='student_form.studentstate')),
            ],
            options={
                'unique_together': {('student', 'day')},
            },
        ),
    ]
